### PR TITLE
Add information about compression options

### PR DESCRIPTION
**Pull request by programming-wolf**
v2 can compress JavaScript files in three ways, and that has to be
added to the docs. :-)

### CODE REVIEW

**Comment by FND** [comment]
Thanks for this! I like it, but think we can make it a little more, uhm, compact:
https://github.com/faucet-pipeline/faucet-pipeline.github.io/compare/doc_improvements_compact_js...compacting-docs

WDYT?

**Comment by moonglum** [comment]
Thank you 👏 I think we need to clarify (in both versions) that you always need to provide the `--compact` flag when you want compaction. No matter which "level" of compaction you choose.

**Comment by FND** [comment]
Good point, I've updated my branch (which is still just a rough suggestion, so could certainly be improved).

**Comment by moonglum** [comment]
I like it 👍

**Comment by moonglum** [comment]
Thanks 🙇

**Pull request merged**
